### ISSUE TITLE
The extra comma in the Config.json

### ISSUE THREAD

**Issue by ScottLL** [Talc-AI/talc-docs#1]
in the config.json 

"fail_criteria": [
      "If the response contains 'as an AI language model' or similar.",
      "If the answer references 'the talk', 'the article', 'the sources', or similar when the question does not contain such references.",
            ]

in the end of the second criteria, there's an extra `,` which might cost the error run. might need to get rid of it.

**Comment by rmkerr** [comment]
Fixed! Thanks Scott!
